 function x_rec = compute_istft(X, stft_params)
 
     x_rec = istft(X, ...
         'Window', stft_params.window, ...
         'OverlapLength', ...
             stft_params.frameLen - stft_params.hopLen, ...
         'FFTLength', stft_params.nfft);
 end

